### ISSUE TITLE
[Visual QA] Sponsors page

### ISSUE THREAD

**Issue by mindywagner** [vigetlabs/npm#188]
https://www.nationalpublicmedia.com/podcastsponsors/

**Visual**
- [x] "1 Code" text should be 12px/#707070
- [x] "Show offers only" text should be 14px
- [ ] Red arrow should point up when the element is expanded, indicating that you can click it again to close the element 
- [ ] Reset Search button text should be consistent with "Micro Button" styles in the Master Components/Styles board (14px bold) - NOTE: This update should be made to all micro buttons - currently anywhere we have a  "View All" or "Load More" button - Services landing, Services detail, Format template, News/Insights block. Related Work block
- ~[ ] Filter by Podcadst form element is missing arrow indicator~
- ~[ ] The bottom half of the expanded state has a scroll bar in it, which it shouldn't need~
- [x] At medium breakpoints, push "Ends X/X/X" to the left flush with all other content
Build example:
<img width="865" alt="Screen Shot 2019-11-21 at 12 08 38 PM" src="https://user-images.githubusercontent.com/67819/69360009-c11fdb80-0c57-11ea-8520-ac5a9cceaef9.png">

**Functional**

- [ ] Reset Search should clear out the keyword & dropdown selection

**Comment by gracecanfield** [comment]
@justinvandenberg One functional/content question: I thought you'd mentioned that you added all sponsors as content in the CMS, but I'm seeing way fewer than what they have on the current site. I think it's fine to put the onus of adding the rest on NPM since we're not responsible for content entry, but I want to make sure I understand the current state of things: 

>* [ ] There is no more "Show More Sponsors" button at the bottom of the page (see original - https://www.nationalpublicmedia.com/podcastsponsors/) 

☝️ Is that just because there aren't enough sponsors to warrant showing the "show more sponsors"? Do we just need to tell them to add the remainders?

**Comment by jeremyfrank** [comment]
> Filter by Podcadst form element is missing arrow indicator

Can we retest this? The arrow shows for me.

**Comment by jeremyfrank** [comment]
Also can we re-test this one? I didn't see any scrollbars.

> The bottom half of the expanded state has a scroll bar in it, which it shouldn't need

**Comment by mindywagner** [comment]
Both of these look like they've resolved to me, @jeremyfrank
