### ISSUE TITLE
Add image captions

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#242]
* [ ] Hero block
* [ ] Featured image block
* [ ] Image block
* [ ] Homepage quote/image block

**Comment by gracecanfield** [comment]
@mindywagner Assigning to you first for design guidance

**Comment by mindywagner** [comment]
I wrote a ticket for this too - and have added design. It's here: https://github.com/vigetlabs/npm/issues/238

I'm calling them photo credits because we already have a caption field for photos on the basic page, and because this treatment is specifically for credits - captions shouldn't be on top of the photo like this.

**Comment by gracecanfield** [comment]
@mindywagner I saw you just assigned this to me, but the ticket's still closed - I want to make sure you weren't noticing something wrong with the implementation?

**Comment by mindywagner** [comment]
Nope - I got an alert for it, can't remember why - saw I was still assigned to it so reassigned to you. Sorry for the confusion!
