### ISSUE TITLE
Embedded audio: Audio loading before user presses play (causing slow-loading)

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#266]
**Audio is loading before pressing play, which is significantly bogging down page load time.**

Example URL:
https://live-national-public-media-v2.pantheonsite.io/work/wellsfargo/

**Comment by jeremyfrank** [comment]
[According to this](https://wavesurfer-js.org/faq/) we have to load the entire file in order to draw the waveform. The `load()` method does have a [preload parameter](https://wavesurfer-js.org/docs/methods.html) with a `none` option, but it only works if you disable the peaks option with an empty array.

Soooooo, to fix this performance issue our options are:

1. Find a WP plugin that can generate the waveform data on the server, then we can initialize the player with the waveform data and set preload (the mp3) to none.
2. Redesign those cards to _only_ show a play button, that when clicked, initializes the player and loads the audio file.

/cc-ing @justinvandenberg in case he has any other ideas.

**Comment by gracecanfield** [comment]
@jeremyfrank Do we have any idea what LOE option 1 would entail? I think option 2 should be iceboxed because it'd be a whooole can of worms.

**Comment by jeremyfrank** [comment]
IF it's even possible with WP, and IF it's achievable with their host Pantheon, I'd guesstimate medium to high LOE. Option 2 would be a lot less time honestly.

**Comment by gracecanfield** [comment]
Okay - in that case, i think we should icebox this for now, since this was an internal-only request. I'm going to move to our "potentially revisit later" milestone and close out.

**Comment by jeremyfrank** [comment]
Just to document it, the MP3s on that page represent an additional 6.3 MB of overall page weight.
