### ISSUE TITLE
Estimate URL structure for sponsorship pages

### ISSUE THREAD

**Issue by haleyjohnso** [vigetlabs/npm#304]
## To Do

In 30 min of exploration:
* Define technical approach to solving this issue
* Estimate the time for the task described below

## Overview

**Page or Element Name** - Sponsorship pages

**Example URL**
https://www.nationalpublicmedia.com/sponsorship/radio-sponsorship/
https://www.nationalpublicmedia.com/sponsorship/podcast-sponsorship/
https://www.nationalpublicmedia.com/sponsorship/voice-sponsorship/
https://www.nationalpublicmedia.com/sponsorship/public-television/
https://www.nationalpublicmedia.com/sponsorship/how-i-built-this-summit/
https://www.nationalpublicmedia.com/sponsorship/tiny-desk-contest/

**Related Trello card**
https://trello.com/c/FGXLNijz
	
## Details

**Summary:** Make all Sponsorship pages child pages of the Platform pages they relate to.  

**Current vs. Desired state:**
Currently, sponsorship pages have the URL structure .../sponsorship/[page-title]. Desired state is .../[platform]/[page-title] - for example https://www.nationalpublicmedia.com/audio/radio-sponsorship/

**Screenshots**
n/a

**Comment by ten1seven** [comment]
WordPress pretty heavily expects to see pages at the root level. Serialized things like posts, categories, and custom post types all have "archive" pages so that WordPress can better use the URL structure to understand how to fetch content. For example, `/sponsorship/` matches a custom post type, so WP knows to serve a "listing" (aka. archive) page. `/sponsorship/radio-sponsorship/` matches the custom post type `sponsorship` so WP knows to serve a single sponsorship post that matches `radio-sponsorship`.

The request here is to use a custom category (ex. `/audio`) at the root level like a page. This is difficult to impossible to get working or working well in an automated way (eg. writing some code that would automatically make all top-level platform slugs be interpreted to do something special). Maybe as important is that this would be magically working behind the scenes in a way that would be confusing for future content editors and developers (eg. making a real page at `/audio` would create a conflict and there would be no feedback as to why or a way to prevent it from happening). There is a potential path forward on this but I will put a hefty number on it with the caveat that getting into might reveal that it's not feasible.

Estimate: **40 hours**

More realistically, I would recommend manually creating pages at all of these locations and we create a new "template" that duplicates the layout of the sponsorship detail page. The process would be:

* Create a page using a new "sponsorship" template at the desired URL.
* There would be only be a single dropdown on that admin page to select the sponsorship content to map to that URL.

On the Viget side, we would simply duplicate the sponsorship template to use as a new page template.

This has the benefit of working with how WordPress works. These pages would sit within the pages admin area for visibility and would be protected from accidental duplication by WordPress' built-in safeguards.

Estimate: **4 hours**

_Note that there are automatic redirects that might need to be updated (ex. `/audio/` forwards to`/products/audio-interstitial/`)._

**Comment by ten1seven** [comment]
Edit: revised my high estimate down to 32 hours

**Comment by gracecanfield** [comment]
Thanks! I followed up with Whitney accordingly.
